//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2.EntityFramework_Models.WhithKeys
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEmailVerifications
    {
        public System.Guid UserId { get; set; }
        public System.Guid Url { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
